services:
  - type: web
    name: fabric-sql-analytics
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port 8002
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FABRIC_SQL_ENDPOINT
        sync: false
      - key: FABRIC_DATABASE
        sync: false
      - key: FABRIC_CLIENT_ID
        sync: false
      - key: FABRIC_CLIENT_SECRET
        sync: false
      - key: FABRIC_TENANT_ID
        sync: false
      - key: AZURE_OPENAI_KEY
        sync: false
      - key: AZURE_OPENAI_API_VERSION
        sync: false
      - key: AZURE_OPENAI_ENDPOINT
        sync: false
      - key: AZURE_OPENAI_DEPLOYMENT
        sync: false 
